import { useCallback, useEffect, useRef, useState } from "react";
import { Clock3, Download, FileText, LoaderCircle, MessageSquare, Paperclip, Pencil, Send, Trash2, Upload } from "lucide-react";
import { inventoryDocumentsApi } from "@/api/inventoryDocumentsApi";
import { getApiErrorMessage } from "@/api/sozlamalarApi";
import type { DocumentAttachment, DocumentComment, DocumentHistory, HistoryChange, InventoryDocumentType } from "@/types/inventoryDocuments";

const accept=".jpg,.jpeg,.png,.webp,.gif,.pdf,.doc,.docx,.xls,.xlsx";
const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif","application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]);
const actionLabels: Record<string,string>={CREATED:"Hujjat yaratildi",UPDATED:"Hujjat yangilandi",CONFIRMED:"Hujjat tasdiqlandi",CANCELLED:"Hujjat bekor qilindi",SENT:"Hujjat jo'natildi",RECEIVED:"Hujjat qabul qilindi",COMMENT_ADDED:"Izoh qo'shildi",COMMENT_UPDATED:"Izoh yangilandi",COMMENT_DELETED:"Izoh o'chirildi",ATTACHMENT_UPLOADED:"Fayl yuklandi",ATTACHMENT_DELETED:"Fayl o'chirildi"};
function userName(user: {fullName?:string;username?:string}|null){return user?.fullName||user?.username||"Tizim"}
function date(value:string){return new Intl.DateTimeFormat("uz-UZ",{dateStyle:"short",timeStyle:"short"}).format(new Date(value))}
function changeText(change:HistoryChange){const field=change.field.replace(/^items\.[^.]+\.?/,"Mahsulot ").replace("actualQuantity","haqiqiy miqdori").replace("quantity","miqdori").replace("price","narxi"); if(change.oldValue==null)return `${field} qo'shildi: ${String(change.newValue??"")}`; if(change.newValue==null)return `${field} o'chirildi`; return `${field}: ${String(change.oldValue)} → ${String(change.newValue)}`}

export default function InventoryDocumentActivity({documentType,documentId}:{documentType:InventoryDocumentType;documentId:string}){
 const [comments,setComments]=useState<DocumentComment[]>([]),[attachments,setAttachments]=useState<DocumentAttachment[]>([]),[history,setHistory]=useState<DocumentHistory[]>([]);
 const [text,setText]=useState(""),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""); const input=useRef<HTMLInputElement>(null);
 const reload=useCallback(async()=>{setError("");try{const [c,a,h]=await Promise.all([inventoryDocumentsApi.comments(documentType,documentId,{page:1,pageSize:100}),inventoryDocumentsApi.attachments(documentType,documentId),inventoryDocumentsApi.history(documentType,documentId,{page:1,pageSize:100})]);setComments(c.items);setAttachments(a);setHistory(h.items)}catch(e){setError(getApiErrorMessage(e))}finally{setLoading(false)}},[documentId,documentType]);
 useEffect(()=>{setLoading(true);void reload()},[reload]);
 async function save(){const clean=text.trim();if(!clean||busy)return;setBusy(true);setError("");try{if(editing)await inventoryDocumentsApi.commentUpdate(documentType,documentId,editing,clean);else await inventoryDocumentsApi.commentCreate(documentType,documentId,{text:clean});setText("");setEditing(null);await reload()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false)}}
 async function removeComment(id:string){if(!window.confirm("Izoh o'chirilsinmi?"))return;setBusy(true);try{await inventoryDocumentsApi.commentDelete(documentType,documentId,id);await reload()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;if(file.size>10*1024*1024)return setError("Fayl hajmi 10 MB dan oshmasligi kerak.");if(!allowed.has(file.type))return setError("Bu fayl formatiga ruxsat berilmagan.");setBusy(true);try{await inventoryDocumentsApi.upload(documentType,documentId,file);await reload()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false);if(input.current)input.current.value=""}}
 async function removeFile(id:string){if(!window.confirm("Fayl o'chirilsinmi?"))return;setBusy(true);try{await inventoryDocumentsApi.attachmentDelete(documentType,documentId,id);await reload()}catch(e){setError(getApiErrorMessage(e))}finally{setBusy(false)}}
 if(loading)return <div className="flex justify-center py-8"><LoaderCircle className="animate-spin text-orange-500"/></div>;
 return <div className="grid gap-5 xl:grid-cols-2">
  <section className="rounded-[26px] border border-orange-100 bg-white p-5 shadow-sm"><Title icon={<MessageSquare size={18}/>} text="Kommentariya"/>{error&&<p className="mb-3 text-sm font-bold text-red-600">{error}</p>}<div className="flex gap-2"><textarea value={text} onChange={e=>setText(e.target.value)} rows={3} placeholder="Izoh yozing..." className="min-w-0 flex-1 resize-none rounded-2xl border border-slate-200 p-3 outline-none focus:border-orange-400"/><button onClick={()=>void save()} disabled={!text.trim()||busy} className="h-11 self-end rounded-xl bg-orange-500 px-4 text-white disabled:opacity-40">{busy?<LoaderCircle size={17} className="animate-spin"/>:<Send size={17}/>}</button></div><div className="mt-4 space-y-3">{comments.map(c=><article key={c.id} className="rounded-2xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-black text-slate-700">{userName(c.author)}</p><p className="text-xs text-slate-400">{date(c.createdAt)}</p></div><div className="flex gap-1">{c.canEdit&&<button onClick={()=>{setEditing(c.id);setText(c.text)}} className="p-2 text-slate-400 hover:text-orange-500"><Pencil size={15}/></button>}{c.canDelete&&<button onClick={()=>void removeComment(c.id)} className="p-2 text-red-400"><Trash2 size={15}/></button>}</div></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{c.text}</p></article>)}{!comments.length&&<p className="py-4 text-center text-sm text-slate-400">Izohlar mavjud emas</p>}</div></section>
  <section className="rounded-[26px] border border-orange-100 bg-white p-5 shadow-sm"><Title icon={<Clock3 size={18}/>} text="Tarix"/><div className="space-y-4">{history.map(h=><div key={h.id} className="flex gap-3"><span className="mt-2 h-2.5 w-2.5 shrink-0 rounded-full bg-orange-500"/><div><p className="text-sm font-black text-slate-700">{actionLabels[h.action]||h.action}</p><p className="text-xs text-slate-400">{userName(h.actor)} · {date(h.createdAt)}</p>{h.changes?.map((c,i)=><p key={i} className="mt-1 text-xs text-slate-500">{changeText(c)}</p>)}</div></div>)}{!history.length&&<p className="text-sm text-slate-400">Tarix mavjud emas</p>}</div></section>
  <section className="rounded-[26px] border border-orange-100 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><Title icon={<Paperclip size={18}/>} text="Biriktirilgan fayllar"/><button onClick={()=>input.current?.click()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 text-sm font-black text-white"><Upload size={16}/>Fayl yuklash</button><input ref={input} hidden type="file" accept={accept} onChange={e=>void upload(e.target.files?.[0])}/></div><div className="mt-3 space-y-2">{attachments.map(a=><div key={a.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div className="flex min-w-0 items-center gap-2"><FileText size={17} className="text-orange-500"/><span className="truncate text-sm font-bold text-slate-700">{a.originalName||a.fileName}</span><span className="text-xs text-slate-400">{(a.size/1024).toFixed(a.size>1048576?0:1)} {a.size>1048576?"MB":"KB"}</span></div><div className="flex"><button onClick={()=>void inventoryDocumentsApi.download(documentType,documentId,a)} className="p-2 text-slate-500"><Download size={16}/></button>{a.canDelete&&<button onClick={()=>void removeFile(a.id)} className="p-2 text-red-400"><Trash2 size={16}/></button>}</div></div>)}{!attachments.length&&<p className="py-3 text-center text-sm text-slate-400">Fayllar mavjud emas</p>}</div></section>
 </div>
}
function Title({icon,text}:{icon:React.ReactNode;text:string}){return <div className="mb-4 flex items-center gap-2 border-b border-orange-100 pb-3 text-sm font-black uppercase text-slate-600"><span className="text-orange-500">{icon}</span>{text}</div>}
