import type { KassaAmaliyoti } from "./types";

export const mockAmaliyotlar: KassaAmaliyoti[] = [
  // --- Naqd tushumlari ---
  {
    id: "ks-1",
    kanal: "naqd",
    yonalish: "tushum",
    turi: "xaridor_tolovi",
    xaridorId: "xrd-1",
    raqam: "FP1",
    nomi: "Savdo tushumi",
    kontragent: "Rahimov Sardor",
    summa: 2000,
    sana: "2026-07-14T17:40:00",
    masul: "Jasur Karimov",
    izoh: "57463423 savdo bo'yicha",
  },
  {
    id: "ks-2",
    kanal: "naqd",
    yonalish: "tushum",
    turi: "donalik_savdo",
    raqam: "FP2",
    nomi: "Kunlik donalik savdo",
    kontragent: "Donalik mijoz",
    summa: 1850000,
    sana: "2026-07-13T19:05:00",
    masul: "Dilnoza Yusupova",
    izoh: "Smena yakuni",
  },
  {
    id: "ks-3",
    kanal: "naqd",
    yonalish: "tushum",
    turi: "boshqa_kirim",
    raqam: "FP3",
    nomi: "Qarz qaytarildi",
    kontragent: "Zamin Market",
    summa: 450000,
    sana: "2026-07-08T11:20:00",
    masul: "Otabek Nazarov",
    izoh: "",
  },

  // --- Naqd chiqimlari ---
  {
    id: "ks-4",
    kanal: "naqd",
    yonalish: "chiqim",
    turi: "xarajat",
    raqam: "FP4",
    nomi: "Ijara to'lovi",
    kontragent: "Chilonzor filiali",
    summa: 3200000,
    sana: "2026-07-05T10:00:00",
    masul: "Jasur Karimov",
    izoh: "Iyul oyi uchun",
  },
  {
    id: "ks-5",
    kanal: "naqd",
    yonalish: "chiqim",
    turi: "taminot_tolovi",
    raqam: "FP5",
    nomi: "Yetkazib beruvchiga to'lov",
    kontragent: "Baraka Oziq-ovqat",
    summa: 980000,
    sana: "2026-06-30T16:30:00",
    masul: "Dilnoza Yusupova",
    izoh: "Un va yormalar kirimi",
  },

  // --- Kiruvchi bank to'lovlari ---
  {
    id: "ks-6",
    kanal: "bank",
    yonalish: "tushum",
    turi: "boshqa_kirim",
    raqam: "FP6",
    nomi: "Pul o'tkazmasi",
    kontragent: "Oq Yo'l Savdo MChJ",
    summa: 480000,
    sana: "2026-06-28T11:05:00",
    masul: "Dilnoza Yusupova",
    izoh: "57460018 savdo to'lovi",
  },
  {
    id: "ks-7",
    kanal: "bank",
    yonalish: "tushum",
    turi: "boshqa_kirim",
    raqam: "FP7",
    nomi: "Shartnoma bo'yicha to'lov",
    kontragent: "Global Trade Group",
    summa: 5200000,
    sana: "2026-06-21T09:45:00",
    masul: "Otabek Nazarov",
    izoh: "",
  },

  // --- Chiquvchi bank to'lovlari ---
  {
    id: "ks-8",
    kanal: "bank",
    yonalish: "chiqim",
    turi: "taminot_tolovi",
    raqam: "FP8",
    nomi: "Ta'minotchiga to'lov",
    kontragent: "Nestle Uzbekistan",
    summa: 4500000,
    sana: "2026-07-12T10:15:00",
    masul: "Jasur Karimov",
    izoh: "88012345 kirim bo'yicha",
  },
  {
    id: "ks-9",
    kanal: "bank",
    yonalish: "chiqim",
    turi: "xarajat",
    raqam: "FP9",
    nomi: "Soliq to'lovi",
    kontragent: "Davlat soliq xizmati",
    summa: 1750000,
    sana: "2026-07-01T12:00:00",
    masul: "Otabek Nazarov",
    izoh: "II chorak",
  },

  // --- Ilova orqali tushumlar ---
  {
    id: "ks-10",
    kanal: "ilova",
    yonalish: "tushum",
    turi: "xaridor_tolovi",
    xaridorId: "xrd-2",
    raqam: "FP10",
    nomi: "Click orqali to'lov",
    kontragent: "Karimova Dilnoza",
    summa: 320000,
    sana: "2026-07-10T14:22:00",
    masul: "Jasur Karimov",
    izoh: "Onlayn buyurtma",
  },
  {
    id: "ks-11",
    kanal: "ilova",
    yonalish: "tushum",
    turi: "xaridor_tolovi",
    xaridorId: "xrd-3",
    raqam: "FP11",
    nomi: "Payme orqali to'lov",
    kontragent: "To'xtayev Jasur",
    summa: 150000,
    sana: "2026-07-09T18:10:00",
    masul: "Dilnoza Yusupova",
    izoh: "",
  },

  // --- Ilova orqali chiqimlar ---
  {
    id: "ks-12",
    kanal: "ilova",
    yonalish: "chiqim",
    turi: "xarajat",
    raqam: "FP12",
    nomi: "Onlayn xizmat obunasi",
    kontragent: "Hosting provayder",
    summa: 240000,
    sana: "2026-07-03T09:30:00",
    masul: "Otabek Nazarov",
    izoh: "Yillik obuna",
  },
  {
    id: "ks-13",
    kanal: "ilova",
    yonalish: "chiqim",
    turi: "xarajat",
    raqam: "FP13",
    nomi: "Reklama to'lovi",
    kontragent: "Marketing agentligi",
    summa: 600000,
    sana: "2026-06-27T15:00:00",
    masul: "Jasur Karimov",
    izoh: "Iyun kampaniyasi",
  },
];
