import { useEffect, useState } from "react";
import { CreditCard, KeyRound, LoaderCircle, Printer, Send } from "lucide-react";
import { integratsiyalarApi, type PrinterIntegratsiya, type TelegramIntegratsiya, type TolovIntegratsiyasi, type TolovProvayderi } from "@/api/integrationsApi";
import { getApiErrorMessage } from "@/api/sozlamalarApi";
import { BolimKarta, SaqlashTugma, Switch } from "./UmumiyUI";
import { maydonKlass } from "./yordamchilar";

const provayderlar: Array<{ id: TolovProvayderi; nomi: string; tavsif: string }> = [
  { id: "PAYME", nomi: "Payme", tavsif: "Payme orqali onlayn to'lovlarni qabul qilish." },
  { id: "CLICK", nomi: "Click", tavsif: "Click to'lov tizimi integratsiyasi." },
  { id: "UZUM", nomi: "Uzum Nasiya", tavsif: "Uzum orqali to'lov va bo'lib to'lash." },
];

export default function IntegratsiyaBolimi() {
  const [tolovlar, setTolovlar] = useState<Record<TolovProvayderi, TolovIntegratsiyasi | null>>({ PAYME: null, CLICK: null, UZUM: null });
  const [sirlar, setSirlar] = useState<Record<TolovProvayderi, string>>({ PAYME: "", CLICK: "", UZUM: "" });
  const [tg, setTg] = useState<TelegramIntegratsiya>({}); const [printer, setPrinter] = useState<PrinterIntegratsiya>({});
  const [yuklanmoqda, setYuklanmoqda] = useState(true); const [saqlanmoqda, setSaqlanmoqda] = useState("");
  const [xato, setXato] = useState(""); const [xabar, setXabar] = useState("");

  useEffect(() => {
    Promise.all([integratsiyalarApi.telegramOlish(), integratsiyalarApi.printerOlish(), ...provayderlar.map((p) => integratsiyalarApi.tolovOlish(p.id))])
      .then(([telegram, printerData, payme, click, uzum]) => { setTg(telegram as TelegramIntegratsiya); setPrinter(printerData as PrinterIntegratsiya); setTolovlar({ PAYME: payme as TolovIntegratsiyasi, CLICK: click as TolovIntegratsiyasi, UZUM: uzum as TolovIntegratsiyasi }); })
      .catch((error) => setXato(getApiErrorMessage(error))).finally(() => setYuklanmoqda(false));
  }, []);

  function xabarlarniTozalash() { setXato(""); setXabar(""); }
  async function tolovSaqlash(provider: TolovProvayderi) {
    const item = tolovlar[provider]; if (!item) return; setSaqlanmoqda(provider); xabarlarniTozalash();
    try { const secretKey = sirlar[provider].trim(); const saved = await integratsiyalarApi.tolovYangilash(provider, { merchantId: item.merchantId?.trim() || "", serviceId: provider === "CLICK" ? item.serviceId?.trim() || "" : undefined, secretKey: secretKey || undefined, isActive: Boolean(item.isActive) }); setTolovlar((s) => ({ ...s, [provider]: saved })); setSirlar((s) => ({ ...s, [provider]: "" })); setXabar(`${provider} integratsiyasi backendga saqlandi.`); } catch (error) { setXato(getApiErrorMessage(error)); } finally { setSaqlanmoqda(""); }
  }
  async function telegramSaqlash() { setSaqlanmoqda("telegram"); xabarlarniTozalash(); try { setTg(await integratsiyalarApi.telegramYangilash({ botToken: tg.botToken ?? undefined, chatId: tg.chatId ?? undefined, isActive: Boolean(tg.isActive), crmBotEnabled: Boolean(tg.crmBotEnabled) })); setXabar("Telegram integratsiyasi backendga saqlandi."); } catch (error) { setXato(getApiErrorMessage(error)); } finally { setSaqlanmoqda(""); } }
  async function printerSaqlash() { setSaqlanmoqda("printer"); xabarlarniTozalash(); try { setPrinter(await integratsiyalarApi.printerYangilash({ ipAddress: printer.ipAddress ?? undefined, port: Number(printer.port || 0) || undefined, isActive: Boolean(printer.isActive) })); setXabar("Printer integratsiyasi backendga saqlandi."); } catch (error) { setXato(getApiErrorMessage(error)); } finally { setSaqlanmoqda(""); } }

  if (yuklanmoqda) return <BolimKarta sarlavha="Integratsiya" izoh="Real integratsiyalar yuklanmoqda."><div className="flex h-48 items-center justify-center gap-2 text-sm font-bold text-slate-400"><LoaderCircle className="animate-spin" size={20}/>Yuklanmoqda...</div></BolimKarta>;
  return <div className="space-y-5">
    {xato && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-600">{xato}</p>}{xabar && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-600">{xabar}</p>}
    <BolimKarta sarlavha="To'lov tizimlari" izoh="Payme, Click va Uzum sozlamalari real backend orqali boshqariladi."><div className="space-y-3">{provayderlar.map((p) => { const item = tolovlar[p.id]; if (!item) return null; return <div key={p.id} className="rounded-2xl border border-orange-100 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-[#FF6A00]"><CreditCard size={18}/></span><div><p className="font-black text-gray-800">{p.nomi}<StatusBelgi ulangan={Boolean(item.isActive)}/></p><p className="text-xs text-gray-400">{p.tavsif}</p></div></div><Switch yoniq={Boolean(item.isActive)} onChange={() => setTolovlar((s) => ({ ...s, [p.id]: { ...item, isActive: !item.isActive } }))}/></div><div className={`mt-3 grid gap-3 ${p.id === "CLICK" ? "lg:grid-cols-3" : "lg:grid-cols-2"}`}><input value={item.merchantId ?? ""} onChange={(e) => setTolovlar((s) => ({ ...s, [p.id]: { ...item, merchantId: e.target.value } }))} placeholder="Merchant ID" className={maydonKlass}/>{p.id === "CLICK" && <input value={item.serviceId ?? ""} onChange={(e) => setTolovlar((s) => ({ ...s, [p.id]: { ...item, serviceId: e.target.value } }))} placeholder="Service ID" className={maydonKlass}/>}<div className="relative"><KeyRound size={16} className="absolute left-3 top-3.5 text-slate-400"/><input type="password" value={sirlar[p.id]} onChange={(e) => setSirlar((s) => ({ ...s, [p.id]: e.target.value }))} placeholder={item.hasSecretKey ? "Maxfiy kalit saqlangan" : "Maxfiy kalit"} className={`${maydonKlass} pl-10`}/></div></div><div className="mt-3 flex justify-end"><SaqlashTugma disabled={saqlanmoqda === p.id} onClick={() => void tolovSaqlash(p.id)}/></div></div>; })}</div></BolimKarta>
    <BolimKarta sarlavha="Telegram bot" izoh="Bildirishnoma va CRM botining real backend sozlamalari." amal={<SaqlashTugma disabled={saqlanmoqda === "telegram"} onClick={() => void telegramSaqlash()}/>}><div className="rounded-2xl border border-orange-100 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-sky-500"><Send size={18}/></span><div><p className="font-black text-gray-800">Telegram bot<StatusBelgi ulangan={Boolean(tg.isActive)}/></p><p className="text-xs text-gray-400">Bot token va chat ID backenddan olinadi.</p></div></div><Switch yoniq={Boolean(tg.isActive)} onChange={() => setTg((s) => ({ ...s, isActive: !s.isActive }))}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={tg.botToken ?? ""} onChange={(e) => setTg((s) => ({ ...s, botToken: e.target.value }))} placeholder="Bot token" className={maydonKlass}/><input value={tg.chatId ?? ""} onChange={(e) => setTg((s) => ({ ...s, chatId: e.target.value }))} placeholder="Chat ID" className={maydonKlass}/></div><label className="mt-3 flex items-center gap-2 text-sm font-bold text-slate-600"><input type="checkbox" checked={Boolean(tg.crmBotEnabled)} onChange={(e) => setTg((s) => ({ ...s, crmBotEnabled: e.target.checked }))} className="h-4 w-4 accent-orange-500"/>CRM bot faol</label></div></BolimKarta>
    <BolimKarta sarlavha="Chek printeri" izoh="Tarmoq printerining real backend sozlamalari." amal={<SaqlashTugma disabled={saqlanmoqda === "printer"} onClick={() => void printerSaqlash()}/>}><div className="rounded-2xl border border-orange-100 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-50 text-[#FF6A00]"><Printer size={18}/></span><div><p className="font-black text-gray-800">Tarmoq printeri<StatusBelgi ulangan={Boolean(printer.isActive)}/></p><p className="text-xs text-gray-400">IP manzil va port orqali ulanadi.</p></div></div><Switch yoniq={Boolean(printer.isActive)} onChange={() => setPrinter((s) => ({ ...s, isActive: !s.isActive }))}/></div><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_160px]"><input value={printer.ipAddress ?? ""} onChange={(e) => setPrinter((s) => ({ ...s, ipAddress: e.target.value }))} placeholder="192.168.1.100" className={maydonKlass}/><input type="number" value={printer.port ?? ""} onChange={(e) => setPrinter((s) => ({ ...s, port: e.target.value ? Number(e.target.value) : null }))} placeholder="9100" className={maydonKlass}/></div></div></BolimKarta>
  </div>;
}
function StatusBelgi({ ulangan }: { ulangan: boolean }) { return <span className={`ml-2 rounded-full px-2 py-0.5 text-xs font-bold ${ulangan ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-500"}`}>{ulangan ? "Ulangan" : "Ulanmagan"}</span>; }
